# Generated by Django 5.2.4 on 2025-10-07 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('heure', models.CharField(max_length=40)),
                ('motif', models.TextField()),
                ('dcr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='changement_nom_prernom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_avant', models.CharField(max_length=25)),
                ('prenom_avant', models.CharField(max_length=25)),
                ('nom_apr', models.CharField(max_length=25)),
                ('prenom_apr', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='classe01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(default='Suppr_Error', max_length=110, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='contact01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('qui', models.CharField(default='', max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='emplous_temps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80)),
                ('emplois', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Filiere01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(default='Suppr_Error', max_length=110, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(default='pas de matiere !', max_length=110)),
            ],
        ),
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('type', models.CharField(default='.', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='pub0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=23)),
                ('pub', models.ImageField(max_length=255, upload_to='')),
                ('message', models.TextField()),
                ('dcr', models.CharField(default='non', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupes_crees', to=settings.AUTH_USER_MODEL)),
                ('membres', models.ManyToManyField(related_name='groupe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('signale', models.CharField(default='.', max_length=40)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app01.groupe')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='pas de badge !', max_length=14)),
                ('classe', models.TextField(default='pas de classe !')),
                ('password0', models.TextField(default='pas de mot de passe !')),
                ('matiere', models.TextField(default='pas de classe !')),
                ('heure_de_reception', models.TextField(default=' Null (not defined yet) ')),
                ('dm', models.TextField(default='.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
