# Generated by Django 5.2.4 on 2025-08-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_profile_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annee01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('année', models.CharField(default='Suppr_Error', max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='classe01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.TextField(default='Suppr_Error', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.TextField(default='Suppr_Error', unique=True)),
            ],
        ),
    ]
