# Generated by Django 5.2.4 on 2025-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_annee01_classe01_filiere01'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classe',
            field=models.TextField(default='pas de classe !'),
        ),
        migrations.AddField(
            model_name='profile',
            name='heure_de_reception',
            field=models.TextField(default="pas d'heure de récéption !"),
        ),
        migrations.AddField(
            model_name='profile',
            name='matiere',
            field=models.TextField(default='pas de classe !'),
        ),
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.TextField(default='pas de mot de passe !'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='badge',
            field=models.CharField(default='pas de badge !', max_length=14),
        ),
    ]
