# Generated by Django 5.2.4 on 2025-08-07 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_matiere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annee01',
        ),
    ]
