# Generated by Django 5.2.4 on 2025-08-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_delete_annee01'),
    ]

    operations = [
        migrations.CreateModel(
            name='changement_nom_prernom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_avant', models.CharField(max_length=25)),
                ('prenom_avant', models.CharField(max_length=25)),
                ('nom_apr', models.CharField(max_length=25)),
                ('prenom_apr', models.CharField(max_length=25)),
            ],
        ),
    ]
