# Generated by Django 5.2.4 on 2025-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='emplous_temps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=80)),
                ('emplois', models.TextField()),
            ],
        ),
    ]
