# Generated by Django 5.2.4 on 2025-08-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_emplous_temps'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='type',
            field=models.CharField(default='.', max_length=8),
        ),
    ]
