# Generated by Django 5.2.4 on 2025-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_posts_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('prenom', models.CharField(max_length=25)),
                ('heure', models.CharField(max_length=20)),
                ('motif', models.TextField()),
                ('dcr', models.TextField()),
            ],
        ),
    ]
