# Generated by Django 5.2.4 on 2025-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_certificat'),
    ]

    operations = [
        migrations.CreateModel(
            name='pub0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=23)),
                ('pub', models.ImageField(upload_to='')),
                ('message', models.TextField()),
            ],
        ),
    ]
