# Generated by Django 5.2.4 on 2025-08-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_pub0'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dm',
            field=models.CharField(default='.', max_length=5),
        ),
    ]
