# Generated by Django 5.2.4 on 2025-08-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0013_profile_dm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub0',
            name='dcr',
            field=models.CharField(default='non', max_length=3),
        ),
    ]
