# Generated by Django 5.2.4 on 2025-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_pub0_dcr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='heure_de_reception',
            field=models.TextField(default=' Null (not defined yet) '),
        ),
    ]
