# Generated by Django 5.2.4 on 2025-08-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_profile_heure_de_reception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dm',
            field=models.TextField(default='.'),
        ),
    ]
