# Generated by Django 5.2.4 on 2025-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_profile_dm'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
