# Generated by Django 5.2.4 on 2025-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0017_contact01'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact01',
            name='qui',
            field=models.CharField(default='', max_length=22),
        ),
    ]
