# Generated by Django 5.2.4 on 2025-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_groupe_message_signalement'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signale',
            field=models.CharField(default='.', max_length=40),
        ),
        migrations.DeleteModel(
            name='Signalement',
        ),
    ]
