# Generated by Django 5.2.4 on 2025-09-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_message_signale_delete_signalement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='dcr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='certificat',
            name='heure',
            field=models.CharField(max_length=40),
        ),
    ]
