# Generated by Django 5.2.4 on 2025-10-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0021_alter_certificat_dcr_alter_certificat_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pub0',
            name='pub',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
