# Generated by Django 5.2.4 on 2025-10-05 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_alter_message_image_alter_pub0_pub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password',
            new_name='password0',
        ),
    ]
