# Generated by Django 5.2.4 on 2025-10-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_rename_password_profile_password0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe01',
            name='classe',
            field=models.CharField(default='Suppr_Error', max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='filiere01',
            name='filiere',
            field=models.CharField(default='Suppr_Error', max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='matiere',
            field=models.CharField(default='pas de matiere !', max_length=110),
        ),
    ]
